version: "3.9"

services:
  pg:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=tictactoe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    container_name: redis
    image: redis
    ports:
      - 6378:6379
    networks:
      - app_network
    restart: on-failure

  tictactoe:
    build: .
    command: >
        sh -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      pg:
        condition: service_healthy
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network: